### ISSUE TITLE
Navigation Issue 

### ISSUE THREAD

**Issue by cristino4** [Carechiga/Easy-Recipe-App#23]
When the application is viewed on github pages the navigation buttons don't point to the correct URL's

**Comment by Carechiga** [comment]
Im not sure why this works on live server but not git hub pages. it looked like the pathing for the hrefs on the link elements was slightly off but i changed them and it didn't work. Looks like well need to add jas script to those links instead

**Comment by cristino4** [comment]
I changed the hrefs to include a period in the beginning so that the applications stop trying to go to the root folder
href="./results-page.html"
I think this should work since currently the application is redirecting to the root folder
I tried the fix in the inspector tool and it works. Please review the pull request

**Comment by Carechiga** [comment]
Yeah that's what i had already did. It just took a while for it to update on pages i guess
